### ISSUE TITLE
Q: [ProtoMember] Ids in Base and Inheritors

### ISSUE THREAD

**Issue by Tridy** [countincognito/Company.Dapr#6]
`RegisterRequestBase` property `Name` has `[ProtoMember(1)]`
`RegisterRequest` : `RegisterRequestBase` property `DateOfBirth` has `[ProtoMember(1)]`

since `RegisterRequest` inherits `RegisterRequestBase`, should all the properties have unique `[ProtoMember(X)]`?

**Comment by countincognito** [comment]
As far as I know, the it is only required that the values of the ProtoIncludes that annotate a class do not match any of the ProtoMember values in the same class.

You can see an explanation here:
https://stackoverflow.com/questions/36773802/how-does-protoinclude20-typeofchild-in-protobuf-net-extend-up-the-class-h

As far as I understand it, this is basically a work around in protobuf-net to compensate for protobuf's lack of support for inheritance. There is a fuller explanation here:
https://stackoverflow.com/questions/56988060/questions-regarding-protobuf-net-with-inheritance

Perhaps it would make sense to annotate the ProtoIncludes with three digit numbers instead of two digits.

**Comment by Tridy** [comment]
I see. It looks like an interesting idea to have three-digit numbers. For me, it still feels kind of weird when the IDs of the base and inheritors match, but it is up to everyone how to do it, I guess. Thanks for the explanation.
